var portItemList =[
  {
    "id": "1",
    "type": "0",
    "code": "underground",
    "title": "반지하 실태 보고서",
    "date": "2020.04",
    "thumb": "port-thumb-1.jpg",
    "bigimage": "port_v_1_1.jpg, port_v_1_2.jpg, port_v_1_3.jpg",
    "link": "http://news.khan.co.kr/kh_storytelling/2020/underground/index.html",
    "workField": "기사작성 및 자료 조사(50%), 그래픽 제작(100%), 페이지 개발(100%)",
    "tag": "HTML, CSS, Javascript, D3.js, Data-mapping, R",
    "description": "<p>최초로 반지하의 국내 현황을 보도한 기사를 재가공해 유통한 데이터 분석 기사입니다. </p><p>단독으로 입수한 전국 반지하 현황 데이터를 동단위, 지역구 단위로 검색해 볼 수 있도록 했습니다. 전국 200여개의 시군구의 반지하 현황을 막대 그래프로 그려 수도권 집중도를 확인하고, 특히 반지하 거주 비율이 현저히 높은 서울시의 경우 서울시 지도에 시군구 별 다른 변수의 값을 통해 어떤 지역에 반지하 거주 비율이 높은지를 살펴보았습니다. </p><p>이전에 보도되지 못한 취재일지 및 현장 사진을 르포기사 형태로 재구성하였습니다.</p>",
    "descriptionEng": "<p>A special news article page projected with the Industrial & Economic Dept of Daily News Paper <KyungHyangShinMun>. the article report the story about people who live under the ground. Underground household are just being recognized after the movie <Parasite> became popular.</p><p>I draw colorized map and pole graph with demographic data of Underground household. User can search and see how many neighborhood are live under the ground by their administrative district or election precinct</p>",
    "able": "true"
  },
  {
    "id": "2",
    "type": "0",
    "code": "privacy",
    "title": "도난당한 개인정보 칼이 되어 돌아오다",
    "date": "2020.03",
    "thumb": "port-thumb-11.jpg",
    "bigimage": "port_v_2_1.jpg, port_v_2_2.jpg, port_v_2_3.jpg,port_v_2_4.jpg",
    "link": "http://el.multicampus.com/main/credu/user/course/zu_course_NR_M.jsp?p_subj=A55581#",
    "workField": "기사작성 및 데이터 조사·가공(80%), 그래픽 제작(100%), 페이지 개발(100%)",
    "tag": "HTML, CSS, Javascript, D3.js",
    "description": "<p>잊을 만 하면 보도되는 개인정보 유출 뉴스, 지난 10년간 유출된 개인정보는 몇 건일까요? 저희가 찾아내어 기록한 것만으로 2억 3천만 건이 넘습니다. 개인정보 유출에 대한 경각심을 주기 위해 2000년대 이후 국내에서 발생한 개인정보 유출 사고들을 한자리에 모아봤습니다.</p><p>이 아카이브는 국내 대표 이러닝 업체 멀티캠퍼스와 협력해 진행한 개인정보보안 관련 교육 콘텐츠 중 하나입니다. 아카이브 외에도 영상, 카드뉴스 등 다양한 교육 콘텐츠가 시리즈로 제작됐습니다.</p><p>사고 목록은 방송통신위원회 정보공개청구 및 언론 보도 등을 토대로 정리했습니다. 추가적으로 유출 사건들을 규모, 원인 등 조건에 따라 필터링하여 조회해볼 수 있도록 작업 하였습니다. 취합한 사건 데이터를 분석·정리하여 하단에 소개하고 있습니다.</p><p>완성된 아카이브는 카드버전, 스크롤 버전으로 나뉘어 강의 코스로 임베딩 되었습니다.</p>",
    "descriptionEng": "<p>Archiving project with the Multicampus(E-learning company). We gathered some 'personal Information extrusion cases' data during 2008-2019 in South Korea. After refined the data via google spreadSheet, I visualized them into a timeline graph.</p><p>As hooking, the danger of the crime by exploiting personal information is introduced in the beginning.</p>",
    "able": "true"
  },
  {
    "id": "3",
    "type": "0",
    "code": "virus",
    "title": "21세기 바이러스 총망라",
    "date": "2020.02",
    "thumb": "port-thumb-2.jpg",
    "bigimage": "port_v_3_1.jpg, port_v_3_2.jpg, port_v_3_3.jpg",
    "link": "http://news.khan.co.kr/kh_storytelling/2020/virus/index.html",
    "workField": "데이터 조사·가공(50%), 페이지 개발(100%)",
    "tag": "HTML, CSS, Javascript, leaflet.js",
    "description": "<p>사스, 신종플루, 메르스, 코로나19 등 21세기 이후 전 세계를 흉흉하게 만든 주요 호흡기 전염병들의 확산·대응과정을 정리한 뉴스 서비스 페이지입니다. 코로나19 창궐 초기에 바이러스에 대한 정보를 제공하기 위한 목적으로 속성으로 제작되었으며, 기존의 다른 호흡기 전염병와 코로나19의 특징을 비교하는 것에 초점을 주었습니다.</p><p>이후 leaflet.js 라이브러리를 이용해 코로나19의 전세계 감염 현황을 지도위에 시각화했습니다. 질병관리본부가 제공하는 현황 정보를 크롤링해오는 방식으로 데이터를 실시간 업데이트 했으며, 마지막 데이터 업데이트 날짜는 4월 24일입니다.</p>",
    "descriptionEng": "<p>A story news page project with the International Dept of Daily News Paper <KyungHyangShinMun>. We spread some confirm/death cases of the corona virus over the world map. An interesting story about the virus which have spread worldwide since 21 century also well organized.</p>",
    "able": "true"
  },
  {
    "id": "4",
    "type": "0",
    "code": "minor",
    "title": "당신은 특권을 갖고 있나요, 차별을 받고 있나요",
    "date": "2020.01",
    "thumb": "port-thumb-3.jpg",
    "bigimage": "port_v_4_1.jpg, port_v_4_2.jpg, port_v_4_3.jpg, port_v_4_4.jpg",
    "link": "http://news.khan.co.kr/kh_storytelling/2020/minor/index.html",
    "workField": "페이지 디자인·개발(100%)",
    "tag": "HTML, CSS, Javascript, D3.js",
    "description": "<p>사용자가 설문에 따라 자신의 특권적⇔차별적 정보를 입력하면, 응답 결과를 레이더 차트로 시각화해 보여주는 서비스 페이지입니다. 원형의 레이더 차트는 방향에 따라 위, 아래로 모두 향하는 양면성을 갖고 있습니다. 이러한 레이더 차트를 통해 모든 개인이 어떤 면에서는 특권을 갖고 있더라도, 또 다른 면에서 차별받고 차별하는 존재임을 시각적으로 보여주고자 했습니다.</p><p>인터랙티브 차트는 D3.js로 구현했습니다. 추가적으로 구글 스프레드시트를 DB로 활용해 사용자의 응답 정보를 받아 기록하였고 이를 토대로 연령별, 혹은 성별에 따른 평균치를 사용자가 조회해볼 수 있도록 했습니다. 약 3천명의 사용자들의 설문에 참여했으며, 설문 결과 및 정성 데이터를 추가 보도에 활용했습니다.</p>",
    "descriptionEng": "<p>A special news page project with the social team. With Radar-Chart graphic, we want to explain that every individual has their major and minor properties, which could be make them to be authorized but also to be discriminated by the society.</p><p>Users can make their own unique radar chart by participating simple survey on the page.</p>",
    "able": "true"
  },
  {
    "id": "5",
    "type": "0",
    "code": "labordeath",
    "title": "산업재해, 1748번의 죽음의 기록",
    "date": "2019.11",
    "thumb": "port-thumb-4.jpg",
    "bigimage": "port_v_5_1.jpg, port_v_5_2.jpg, port_v_5_3.jpg, port_v_5_4.jpg, port_v_5_5.jpg",
    "link": "http://news.khan.co.kr/kh_storytelling/2019/labordeath/index.html",
    "workField": "페이지 디자인·기획(100%), 데이터 조사·가공(50%), 페이지 개발(100%), 페이지 내 기사 작성(30%)",
    "tag": "HTML, CSS, Javascript, D3.js, leaflet.js",
    "description": "<p>2018년부터 2019년까지 2년 동안 발생한 산업재해 사망사고를 전수 조사하여 살펴본 데이터 분석 기사입니다. 사망 사고 한 명, 한 명을의 기록을 담은 디지털 아카이브의 기획 및 제작을 담당했습니다.</p><p>한국산업안전보건공단이 작성한 재해조사 의견서 PDF를 입수해 약 2천 건의 사고 정보를 DB화하였습니다. 이 DB를 토대로 D3.js를 이용해 2천 건의 죽음을 사람의 형상으로 시각화했습니다. 사망사고의 50%가 추락사로 인한 사망이었고, 이를 사용자들이 한눈에 확인할 수 있도록 사고 원인 유형에 따라 사람 형상의 색상 및 형태를 다르게 표현했습니다. 사고의 원인 외에도 사망자에 대한 정보, 산업장 규모 등에 따라 분류하여 볼 수 있도록 했습니다.</p><p>캘린더 히트맵 그래픽으로 일별 사망인원의 분포도를 시각화했습니다. 이를 통해 2년의 시간 동안 단 67일을 제외하고 매일 사고가 발생했음을, 하루에 10명이 넘는 사망자가 발생한 날도 있었음을 시사하고자 했습니다.</p><p>Google Map API를 활용해 사고가 발생한 위치의 위경도 값을 찾아내 이를 지도 위에 시각화했습니다.</p>",
    "descriptionEng": "<p>A special news article page archiving thousands of death due to industrial disaster during 2018-2019. SVG graphic and line graph are drawn by D3.js & data mapping by leaflet.js</p>",
    "able": "true"
  },
  {
    "id": "6",
    "type": "0",
    "code": "brandmap",
    "title": "대기업브랜드지도",
    "date": "2019.01",
    "thumb": "port-thumb-5.jpg",
    "bigimage": "port_v_6_1.jpg, port_v_6_2.jpg, port_v_6_3.jpg",
    "link": "http://news.khan.co.kr/kh_storytelling/2018/brandmap/index.html",
    "workField": "페이지 디자인·기획(100%), 데이터 조사(100%), 페이지 개발(50%)",
    "tag": "HTML, CSS, Javascript, D3.js",
    "description": "<p>우리는 하루를 살아가며 다양한 상품을 소비하고, 서비스들을 이용합니다. 그중에 국내 대기업이 소유한 브랜드와 서비스의 지분을 어느 정도일까요? 개인의 소비 생활에서 대기업이 차지하는 비율, 즉 대기업 의존도를 알아보는 기획을 진행하면서 대기업의 브랜드 지도를 그려보았습니다.</p><p>지면 그래픽과 별개로 온라인에서 D3.js의 Hierarchy Bubble Chart를 이용해 대기업 브랜드의 목록을 시각화했습니다. 기업은 공정위가 지정한 대규모 기업집단 중에서도 인지도 있는 제품·브랜드를 비교적 다양한 분야에서 가지고 있는 그룹들을 대상으로 했습니다.</p>",
    "descriptionEng": "<p>An interactive bubble chart to visualize brand map of famous South Korea corporations. A graphic was drawn by d3.js library. Users can move and zoom in/ out by clicking or dragging the map.</p>",
    "able": "true"
  },
  {
    "id": "7",
    "type": "0",
    "code": "korea",
    "title": "남북 70년",
    "date": "2018.04",
    "thumb": "port-thumb-6.jpg",
    "bigimage": "port_v_7_1.jpg, port_v_7_2.jpg, port_v_7_3.jpg, port_v_7_4.jpg, port_v_7_5.jpg",
    "link": "http://news.khan.co.kr/kh_storytelling/2018/korea/index.html",
    "workField": "페이지 디자인·기획(100%), 페이지 개발(100%)",
    "tag": "HTML, CSS, Javascript, D3.js",
    "description": "<p>2018 정상회담을 기념해 사건 발생 때마다 이뤄지는 파편적인 보도를 넘어 70년간 남북관계를 돌아보는 기획을 준비했습니다. 통일연구원에서 발표한 <남북관계연표 1948~2013>를 참고해 중요한 사건 300여개를 추려내 이를 한눈에 보기 쉬운 그래픽으로 제작했습니다.</p><p>시간의 흐름을 X축에 두고 Y축 위에 사건을 뿌렸습니다. 독자들이 그래프를 확대, 축소하며 사건들을 탐험할 수 있게 했습니다. 남북관계에 긍정적인 영향을 준 사건은 파랑색으로, 부정적인 영향을 준 사건은 빨간색으로, 중립적인 성격의 사건의 경우 회색으로 나누어 표현했습니다. 비교적 중요한 사건과 그렇지 않은 사건은 투명도를 다르게 표현해 구분하였습니다. 이를 통해 사용자가 정상회담을 포함해 수많은 남북의 관계와 외교적 사건의 흐름을 파악하게 하는 것이 기획 취지입니다.</p><p>300여개의 사건들 중 같은 분류의 사건들만 따로 볼 수 있도록 사건들을 ‘무력충돌’, ‘남북회담’, ‘이산가족 상봉’, ‘문화 교류’ 등 13개의 분류로 나누습니다. 사용자는 원하는 분류의 사건들만 따로 조회해볼 수 있습니다.</p>",
    "descriptionEng": "<p>A timeline graphic expressing diplomatic relation btw South and North korea by showing hundreds of important event from 1960 to the present. the interactive graphic was drawn by d3.js library.</p>",
    "able": "true"
  },
  {
    "id": "8",
    "type": "0",
    "code": "salary",
    "title": "박전무 대 김대리",
    "date": "2018.04",
    "thumb": "port-thumb-7.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "9",
    "type": "0",
    "code": "elite",
    "title": "고위직 ",
    "date": "2017.08",
    "thumb": "port-thumb-9.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "10",
    "type": "0",
    "code": "cabinet",
    "title": "내각구성",
    "date": "2017.08",
    "thumb": "port-thumb-10.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "11",
    "type": "0",
    "code": "party",
    "title": "대한민국정당사",
    "date": "2017.01",
    "thumb": "port-thumb-28.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "12",
    "type": "1",
    "code": "tracknroom",
    "title": "n번방리와인드",
    "date": "2020.06",
    "thumb": "port-thumb-29.jpg",
    "bigimage": "port_v_12_1.jpg, port_v_12_2.jpg, port_v_12_3.jpg, port_v_12_4.jpg, port_v_12_5.jpg",
    "link": "http://news.khan.co.kr/kh_storytelling/2020/tracknroom/index.html",
    "workField": "페이지 디자인·기획(100%), 페이지 개발(100%)",
    "tag": "HTML, CSS, Javascript, D3.js",
    "description": "<p>2020년 3월 텔레그램에서 벌어진 성착취가 세상에 공개됐고, 사회는 충격에 빠졌습니다. n번방으로 불리는 이 사건은 해킹, 불법촬영, 협박, 유포 등 디지털 공간에서 벌어질 수 있는 성범죄의 종합판이었습니다. 사실 n번방 이전에도 버닝썬, 다크웹, 연예인 단톡방 사건이 있었습니다. n번방은 이렇게 수 많은 디지털 성범죄를 방조한 순간들이 조각조각 모여 만들어진 결과물일지도 모릅니다.</p><p>우리는 n번방을 탄생시킨, 성착취를 가능케 한 사회를 돌아봤습니다. ‘빨간 책’과 ‘빨간 테이프’에서 ‘OO 비디오’, ‘소라넷’, ‘웹하드’, 텔레그램까지 성착취 범죄의 시작을 찾기 위해 시간을 거슬렀습니다. 시작은 성범죄를 ‘정조에 관한 죄’로 규정한 1953년 형법 재정 당시입니다. 그 이후로 발생한 100여 개의 사건, 이벤트, 연결 고리들을 찾아 시간 위에 기록했습니다. 이 페이지는 그렇게 탄생시킨 개별 사건과 사건에 대한 판결(법), 당시 사회 분위기(문화)라는 커다란 세 갈래가 얽혀 있는 디지털 성범죄의 타임라인입니다.</p><p>유관한 사건끼리는 선으로 엮어주어 사용자가 테마별로 사건의 흐름을 쉽게 파악하도록 했습니다. 중요한 사건의 경우 상세한 사건에 대한 설명을 조회해 볼 수 있습니다. 상, 하단의 그래픽 및 사건의 선들은 SVG 요소로 구현되었습니다.</p>",
    "descriptionEng": "<p> N's ROOM REWIND timeline page.</p>",
    "able": "true"
  },
  {
    "id": "13",
    "type": "1",
    "code": "apart",
    "title": "아파트",
    "date": "2019.10",
    "thumb": "port-thumb-12.jpg",
    "bigimage": "port_v_13_1.jpg, port_v_13_2.jpg, port_v_13_3.jpg, port_v_13_4.jpg, port_v_13_5.jpg, port_v_13_6.jpg",
    "link": "http://news.khan.co.kr/kh_news/khan_art_view.html?artid=201910032047002&code=940702",
    "workField": "데이터 조사(50%), 페이지 디자인·기획·개발(100%), 지면기획(30%)",
    "tag": "HTML, CSS, Javascript, scrollMagic.js",
    "description": "<p>우리나라의 국민 50% 이상이 아파트에 거주합니다. 어느새 ‘아파트’라는 주거 공간은 한국의 대표적인 주거공간으로 자리잡고 있습니다. 그런데 ‘집’으로만 여겨졌던 아파트는 ‘일터’이기도 합니다. 24시간 움직이는 경비노동자, 각종 시설을 점검하는 시설관리노동자, 곳곳을 쓸고 닦는 청소노동자…. 매일같이 마주하면서도 제대로 알지 못했던 수많은 노동이 아파트에서 이뤄집니다.</p><p>창간을 맞아 <아파트 노동>을 주제로 인포그래픽형 기사를 제작했습니다. 아파트와 단지를 일터로 삼는 약 서른개의 직업군을 찾아 소개하고, 근로자규모·평균 월급 등을 살펴봤습니다.</p><p>인포그래픽 기사를 가공해 온라인에서도 보기 좋게 재구성 하였습니다. ScrollMagic 라이브러리를 활용해 정적이었던 인포그래픽에 스크롤 값에 따라 애니메이션이 추가되도록 했습니다. 주요 직업군들은 소개 이미지를 2컷 프레임 애니메이션으로 적용하여 살아 움직이는 듯한 효과를 주었습니다.</p>",
    "descriptionEng": null,
    "able": "true"
  },
  {
    "id": "14",
    "type": "1",
    "code": "factory",
    "title": "화학물질",
    "date": "2019.08",
    "thumb": "port-thumb-13.jpg",
    "bigimage": "port_v_14_1.jpg, port_v_14_2.jpg, port_v_14_3.jpg, port_v_14_4.jpg, port_v_14_5.jpg, port_v_14_6.jpg",
    "link": "http://news.khan.co.kr/kh_storytelling/2019/factory/index.html",
    "workField": "데이터 조사·가공(50%), 페이지 기획·개발(100%), 페이지 내 기사 작성(30%)",
    "tag": "HTML, CSS, Javascript, R",
    "description": "<p>비누, 세제, 텔레비전, 식료품…. 오늘도 우리가 사용할 물건들을 만들기 위해 공장은 쉴 새 없이 가동됩니다. 그 과정에서 수많은 화학물질이 사용되고, 때론 위험 화학물질이 포함되죠. 우리는 이제 화학물질과 함께 살 수밖에 없습니다. 그렇기에 사고가 일어나지 않도록 충분히 관리하고 대비를 하는 것이 중요합니다.</p><p>우리나라는 화학물질 중 위험성이 높은 일부 화학물질을 ‘사고대비물질’로 분류해 관리하고 있습니다. 환경부, 노동환경건강연구소와 협력하여 「화학물질통계조사」의 데이터를 제공받아 지역별로 얼마나 많은 ‘사고대비물질’이 취급되고 있는지 현황을 살펴봤습니다.</p><p>「화학물질통계조사」를 토대로 전국 229개 지자체의 화학물질 취급량, 대규모 공장의 개수, 인구수, 산업단지 생산 실적 등을 정리하고 이를 지수화하여 사고대비물질 취급 순위를 구했습니다. 그리고 사용자들이 자신의 지역 현황은 어떠한지 알아볼 수 있도록 이를 검색기 형태로 가공했습니다. 데이터 가공은 GoogleSpreadSheet와 R을 활용했습니다.</p>",
    "descriptionEng": null,
    "able": "true"
  },
  {
    "id": "15",
    "type": "1",
    "code": "genx",
    "title": "X세대 리포트",
    "date": "2019.07",
    "thumb": "port-thumb-14.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "16",
    "type": "1",
    "code": "mayday",
    "title": "그려진 노동",
    "date": "2019.05",
    "thumb": "port-thumb-15.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "17",
    "type": "1",
    "code": "herstory",
    "title": "허스토리",
    "date": "2019.03",
    "thumb": "port-thumb-16.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "18",
    "type": "1",
    "code": "rohingya",
    "title": "로힝야",
    "date": "2019.02",
    "thumb": "port-thumb-17.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "19",
    "type": "1",
    "code": "myact",
    "title": "나어독",
    "date": "2019.02",
    "thumb": "port-thumb-18.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "20",
    "type": "1",
    "code": "whereis",
    "title": "숨은사람찾기",
    "date": "2018.10",
    "thumb": "port-thumb-19.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "21",
    "type": "1",
    "code": "noodle",
    "title": "랭면의취향",
    "date": "2018.07",
    "thumb": "port-thumb-20.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "22",
    "type": "1",
    "code": "ourvote",
    "title": "역대우리동네승자는",
    "date": "2018.06",
    "thumb": "port-thumb-21.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "23",
    "type": "1",
    "code": "metoo100",
    "title": "세상을 고발한여성들",
    "date": "2018.03",
    "thumb": "port-thumb-22.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "24",
    "type": "1",
    "code": "edu",
    "title": "전교1등",
    "date": "2018.01",
    "thumb": "port-thumb-23.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "25",
    "type": "1",
    "code": "policy",
    "title": "후보정책한눈에",
    "date": "2017.04",
    "thumb": "port-thumb-25.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "26",
    "type": "1",
    "code": "tenshot",
    "title": "대선주자 10장면",
    "date": "2017.04",
    "thumb": "port-thumb-26.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "27",
    "type": "2",
    "code": "undergroundG",
    "title": "반지하 상단 그래픽",
    "date": "2020.04",
    "thumb": "port-thumb-30.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "28",
    "type": "2",
    "code": "privacyG",
    "title": "멀티캠퍼스 내부 그래픽",
    "date": "2020.03",
    "thumb": "port-thumb-31.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "29",
    "type": "2",
    "code": "policyG",
    "title": "정당사",
    "date": "2017.01",
    "thumb": "port-thumb-32.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "30",
    "type": "2",
    "code": "bitenews",
    "title": "읽씹뉴스",
    "date": "2019.03",
    "thumb": "port-thumb-33.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "31",
    "type": "3",
    "code": "khyoutube",
    "title": "이런경향",
    "date": "2019.03",
    "thumb": "port-thumb-34.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "32",
    "type": "3",
    "code": "newsming",
    "title": "뉴스밍",
    "date": "2020.04",
    "thumb": "port-thumb-35.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "33",
    "type": "3",
    "code": "khshare",
    "title": "경향신문 공유",
    "date": "2018.02",
    "thumb": "port-thumb-36.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "34",
    "type": "4",
    "code": null,
    "title": "카드뉴스1",
    "date": "2017",
    "thumb": "port-thumb-37.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "35",
    "type": "4",
    "code": null,
    "title": "카드뉴스1",
    "date": "2017",
    "thumb": "port-thumb-38.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "36",
    "type": "5",
    "code": null,
    "title": "영상1",
    "date": "2018",
    "thumb": "port-thumb-39.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
    "id": "37",
    "type": "5",
    "code": null,
    "title": "영상2",
    "date": "2018",
    "thumb": "port-thumb-40.jpg",
    "bigimage": null,
    "link": null,
    "workField": null,
    "tag": null,
    "description": null,
    "descriptionEng": null,
    "able": "FASLE"
  },
  {
	 "id": 38,
	  "code": "climatechange",
	  "title": "기후변화의 증인들",
	  "date": "2020.09",
	  "thumb": "port-thumb-38.jpg",
	  "bigimage": "port_v_38_1.jpg, port_v_38_2.jpg, port_v_38_3.jpg, port_v_38_4.jpg, port_v_38_5.jpg",
	  "link": "http://news.khan.co.kr/kh_storytelling/2020/climatechange/index.html",
	  "workField": "데이터 조사·가공(20%), 페이지 기획·개발(100%)",
	  "tag": "HTML, CSS, Javascript, Three.js, D3.js",
	  "description": "<p>2020년은 한국에 이상기후 현상이 유독 잦았습니다. ‘1년에 한 번’ 정도 발생하던 이상기후 현상이 ‘매 계절마다’ 발생했습니다. 겨울엔 이상고온 현상이, 봄에는 이상고온과 이상저온 현상이 동시에 나타났습니다.</p><p>‘기록적 폭염’이 예고됐던 여름, 폭염 대신 예상치 못한 ‘폭우’가 닥쳤습니다. 역대 최장기간(54일) 동안 지속된, 내린 비의 양(686.9㎜) 역시 역대 두 번째로 많은 장마였습니다. 이번 장마같은 이상기후 현상은 앞으로도 계속 발생할까요? 현 추세대로라면, 아마 그럴 가능성이 높습니다</p><p>경향신문은 올해 누군가에겐 낯설게만 느껴지는 ‘기후변화’를 직접 목격하고 경험한 ‘증인들’을 만나 이야기를 들었습니다. 바다와 땅, 산에서 일하는 이들은 “나는 전문가는 아니지만, 기후변화에 대해 잘 모르지만”이라는 전제를 달고 자신의 경험을 이야기했습니다. 각종 보고서상의 ‘숫자’로 존재하던 것들이 이들에겐 지금 눈앞에서 벌어지는 위기이자 현실이었다.</p><p>그들의 생생한 증언을 담아봤습니다.<p/>",
	  "descriptionEng": null,
	  "able": "true"
  }
]